server:
  port: 8080

spring:
  application:
    name: mortgage-check-api

management:
  endpoints:
    web:
      exposure:
        include: health,info, metrics, prometheus
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

resilience4j.ratelimiter:
  instances:
    apiRateLimiter:
      limit-for-period: 5   # max requests
      limit-refresh-period: 1m  # per minute
      timeout-duration: 0   # fail immediately if limit reached

logging:
  level:
    root: INFO

mortgage:
  incomeMultiplier: 4
  startup:
    rates:
      - maturityPeriod: 5
        interestRate: 3.5
      - maturityPeriod: 10
        interestRate: 3.8
      - maturityPeriod: 20
        interestRate: 4.5